[package]
name = "honkdrop"
type = "bin"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "zpedro/0.36.0", directory = "packages/merkle-trees" }
ecrecover = { tag = "main", git = "https://github.com/signorecello/ecrecover-noir" }
plume = { path = "../../lib/plume" }
noir_bigcurve = { path = "../../lib/noir_bigcurve" }
bignum = { tag = "main", git = "https://github.com/noir-lang/noir-bignum" }
nodash = { tag = "v0.36.0", git = "https://github.com/olehmisar/nodash/" }
