[package]
name = "honkdrop"
type = "bin"
authors = [""]
compiler_version = ">=0.30.0"

[dependencies]
trees = { git = "https://github.com/privacy-scaling-explorations/zk-kit.noir", tag = "zpedro/0.36.0", directory = "packages/merkle-trees" }
ecrecover = { tag = "v0.30.0", git = "https://github.com/signorecello/ecrecover-noir" }
plume = { git = "https://github.com/distributed-lab/noir-plume", tag = "v2.0.0", directory = "crates/plume" }
noir_bigcurve = { tag = "v0.5.0", git = "https://github.com/noir-lang/noir_bigcurve" }
bignum = { tag = "v0.4.1", git = "https://github.com/noir-lang/noir-bignum" }
nodash = { tag = "v0.36.0", git = "https://github.com/olehmisar/nodash/" }
